package com.example.quickbid.quickbid.service;
import java.util.List; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.example.quickbid.quickbid.audit.*; import com.example.quickbid.quickbid.dto.response.UsuarioDtos.CategoryProgress; import com.example.quickbid.quickbid.entity.app.*; import com.example.quickbid.quickbid.repository.app.*; import com.example.quickbid.quickbid.repository.legacy.ClienteRepository;
@Service public class CategoriaService {
 private final CategoriaPuntosRepository categorias; private final MovimientoPuntosRepository movimientos; private final ClienteRepository clientes; private final AuditService audit;
 public CategoriaService(CategoriaPuntosRepository c,MovimientoPuntosRepository m,ClienteRepository cl,AuditService a){categorias=c;movimientos=m;clientes=cl;audit=a;}
 @Transactional public CategoryProgress synchronize(CuentaApp cuenta){List<CategoriaPuntos> all=categorias.findAllByOrderByPuntosMinimosAsc();CategoriaPuntos actual=all.stream().filter(c->c.getPuntosMinimos()<=cuenta.getPuntos()).reduce((a,b)->b).orElseThrow();if(!actual.getCategoria().equals(cuenta.getCategoriaCalculada())){cuenta.updateCategory(actual.getCategoria());clientes.findById(cuenta.getClienteId()).ifPresent(c->c.updateCategory(actual.getCategoria()));audit.record(new AuditEvent("sistema",null,"usuario.categoria_actualizada","cuenta",cuenta.getId(),"{\"categoria\":\""+actual.getCategoria()+"\"}"));}return progress(cuenta.getPuntos(),actual,all);}
 @Transactional public CategoryProgress addPoints(CuentaApp cuenta,int delta,String motivo,String tipo,Long referencia){cuenta.addPoints(delta);movimientos.save(new MovimientoPuntos(cuenta.getId(),delta,motivo,tipo,referencia));return synchronize(cuenta);}
 private CategoryProgress progress(int puntos,CategoriaPuntos actual,List<CategoriaPuntos> all){var next=all.stream().filter(c->c.getOrden()>actual.getOrden()).findFirst();if(next.isEmpty())return new CategoryProgress(actual.getCategoria(),null,puntos,null,0,100);int base=actual.getPuntosMinimos(),target=next.get().getPuntosMinimos();int porcentaje=Math.min(100,Math.max(0,(puntos-base)*100/(target-base)));return new CategoryProgress(actual.getCategoria(),next.get().getCategoria(),puntos,target,Math.max(0,target-puntos),porcentaje);}
}
