package com.example.quickbid.quickbid.service;
import java.math.*; import java.time.*; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.example.quickbid.quickbid.audit.*; import com.example.quickbid.quickbid.dto.request.DireccionEnvioRequest; import com.example.quickbid.quickbid.dto.response.UsuarioDtos.*; import com.example.quickbid.quickbid.entity.app.*; import com.example.quickbid.quickbid.exception.BusinessException; import com.example.quickbid.quickbid.repository.app.*; import com.example.quickbid.quickbid.repository.legacy.PersonaRepository;
@Service public class UsuarioService {
 private final CuentaAppRepository cuentas; private final PersonaRepository personas; private final CategoriaService categorias; private final NotificacionAppRepository notificaciones; private final DireccionEnvioRepository direcciones; private final UsuarioQueryRepository queries; private final AuditService audit;
 public UsuarioService(CuentaAppRepository c,PersonaRepository p,CategoriaService cs,NotificacionAppRepository n,DireccionEnvioRepository d,UsuarioQueryRepository q,AuditService a){cuentas=c;personas=p;categorias=cs;notificaciones=n;direcciones=d;queries=q;audit=a;}
 @Transactional public Profile profile(Long id){var cuenta=account(id);var persona=personas.findById(cuenta.getPersonaId()).orElseThrow();var progreso=categorias.synchronize(cuenta);String[] name=persona.getNombre().trim().split("\\s+",2);boolean multa=cuenta.getEstado().equals("restriccion_multa");return new Profile(cuenta.getId(),name[0],name.length>1?name[1]:"",cuenta.getEmail(),cuenta.getCategoriaCalculada(),cuenta.getPuntos(),progreso,cuenta.getEstado(),multa?"restringida_por_multa":"habilitada",new Permissions(true,!multa,!multa,true,multa));}
 @Transactional(readOnly=true) public Statistics statistics(Long id){account(id);var snapshot=queries.statistics(id);int bids=snapshot.bids(),wins=snapshot.wins();BigDecimal rate=bids==0?BigDecimal.ZERO:BigDecimal.valueOf(wins*100.0/bids).setScale(2,RoundingMode.HALF_UP);return new Statistics(snapshot.totalBid(),snapshot.totalPaid(),rate,snapshot.purchases(),bids,snapshot.auctions(),monthly(id));}
 @Transactional(readOnly=true) public Page<HistoryItem> history(Long id,int page,int size){account(id);checkPage(page,size);return page(queries.findHistory(id,page,size),page,size,queries.countHistory(id));}
 @Transactional(readOnly=true) public Page<Notification> notifications(Long id,String tipo,Boolean leida,int page,int size){account(id);checkPage(page,size);return page(queries.findNotifications(id,tipo,leida,page,size),page,size,queries.countNotifications(id,tipo,leida));}
 @Transactional public Notification readNotification(Long cuentaId,Long id){account(cuentaId);var notification=notificaciones.findByIdAndCuentaId(id,cuentaId).orElseThrow(()->notificaciones.existsById(id)?forbidden():notFound("Notificacion inexistente"));notification.markRead();audit.record(new AuditEvent("usuario",cuentaId,"usuario.notificacion_leida","notificacion",id,"{}"));return notification(notification);}
 @Transactional public List<Notification> readAllNotifications(Long cuentaId){account(cuentaId);var unread=notificaciones.findAllByCuentaIdAndLeidaFalseOrderByCreatedAtDesc(cuentaId);unread.forEach(NotificacionApp::markRead);if(!unread.isEmpty())audit.record(new AuditEvent("usuario",cuentaId,"usuario.notificaciones_leidas","notificacion",null,"{\"cantidad\":"+unread.size()+"}"));return unread.stream().map(this::notification).toList();}
 @Transactional(readOnly=true) public Address address(Long id){account(id);return direcciones.findFirstByCuentaIdAndPrincipalTrueAndDeletedAtIsNull(id).map(this::address).orElse(null);}
 @Transactional public Address updateAddress(Long id,DireccionEnvioRequest r){account(id);var address=direcciones.findFirstByCuentaIdAndPrincipalTrueAndDeletedAtIsNull(id).orElseGet(()->new DireccionEnvio(id));address.update(r.alias(),r.destinatario(),r.calle(),r.numero(),r.piso(),r.codigoPostal(),r.localidad(),r.provincia(),r.pais(),r.telefono());address=direcciones.save(address);audit.record(new AuditEvent("usuario",id,"usuario.direccion_envio_actualizada","direccion_envio",address.getId(),"{}"));return address(address);}
 private CuentaApp account(Long id){return cuentas.findById(id).orElseThrow(()->notFound("Cuenta inexistente"));}
 private List<MonthlyActivity> monthly(Long id){Map<YearMonth,int[]> m=new TreeMap<>();queries.findMonthlyActivity(id).forEach(activity->{YearMonth month=YearMonth.from(activity.createdAt());int[] count=m.computeIfAbsent(month,k->new int[2]);if(activity.type().equals("puja"))count[0]++;else count[1]++;});return m.entrySet().stream().map(e->new MonthlyActivity(e.getKey().toString(),e.getValue()[0],e.getValue()[1])).toList();}
 private Notification notification(NotificacionApp n){return new Notification(n.getId(),n.getTipo(),n.getTitulo(),n.getDescripcion(),n.getReferenciaTipo(),n.getReferenciaId(),n.getLeida(),n.getCreatedAt());}private Address address(DireccionEnvio d){return new Address(d.getId(),d.getAlias(),d.getDestinatario(),d.getCalle(),d.getNumero(),d.getPiso(),d.getCodigoPostal(),d.getLocalidad(),d.getProvincia(),d.getPais(),d.getTelefono());}
 private <T> Page<T> page(List<T> c,int p,int s,long t){return new Page<>(c,p,s,t,(int)Math.ceil((double)t/s));}private void checkPage(int p,int s){if(p<0||s<1||s>100)throw new BusinessException(HttpStatus.BAD_REQUEST,"Paginacion invalida","INVALID_PAGE");}private BusinessException forbidden(){return new BusinessException(HttpStatus.FORBIDDEN,"El recurso no pertenece al usuario","RESOURCE_NOT_OWNED");}private BusinessException notFound(String m){return new BusinessException(HttpStatus.NOT_FOUND,m,"RESOURCE_NOT_FOUND");}
}
