package com.example.quickbid.quickbid;
import static org.junit.jupiter.api.Assertions.*; import static org.hamcrest.Matchers.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.time.LocalDate; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.http.MediaType; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.mock.web.MockMultipartFile; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.context.jdbc.Sql; import org.springframework.test.web.servlet.*; import com.example.quickbid.quickbid.security.AuthRateLimitService; import com.jayway.jsonpath.JsonPath;
@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") @Sql(scripts="/auth-test-data.sql",executionPhase=Sql.ExecutionPhase.BEFORE_TEST_METHOD)
class MedioPagoIntegrationTests {
 @Autowired MockMvc mvc; @Autowired JdbcTemplate jdbc; @Autowired AuthRateLimitService limits; @BeforeEach void clearLimits(){limits.clear();}
 @Test void listaMediosPropios()throws Exception{request(get("/api/usuario/medios-pago"),"aprobado@quickbid.demo").andExpect(status().isOk()).andExpect(jsonPath("$.data",hasSize(3))).andExpect(jsonPath("$.data[0].ultimos4",anyOf(nullValue(),is("4242"))));}
 @Test void creaTarjetaSinPersistirPanNiCvv()throws Exception{request(post("/api/usuario/medios-pago").contentType(MediaType.APPLICATION_JSON).content(card("4111111111111111")),"multa@quickbid.demo").andExpect(status().isCreated()).andExpect(jsonPath("$.data.estado").value("pendiente_verificacion")).andExpect(jsonPath("$.data.ultimos4").value("1111"));String hash=jdbc.queryForObject("SELECT hash_identificador FROM app_medios_pago WHERE ultimos_4='1111'",String.class);assertNotEquals("4111111111111111",hash);assertFalse(hash.contains("123"));}
 @Test void creaCuentaBancaria()throws Exception{String body="{\"tipo\":\"cuenta_bancaria\",\"moneda\":\"ARS\",\"nacional\":true,\"titular\":\"Ana Aprobada\",\"numeroCuenta\":\"123456789\",\"cbuCvu\":\"000123456789\",\"nombreBanco\":\"Banco Demo\",\"alias\":\"ANA.DEMO\"}";request(post("/api/usuario/medios-pago").contentType(MediaType.APPLICATION_JSON).content(body),"aprobado@quickbid.demo").andExpect(status().isCreated()).andExpect(jsonPath("$.data.banco").value("Banco Demo"));}
 @Test void chequeSinFotosEsError()throws Exception{request(multipart("/api/usuario/medios-pago").param("moneda","ARS").param("nacional","true").param("titular","Ana").param("numeroCheque","CH-1").param("monto","1000").param("fechaVencimiento",LocalDate.now().plusDays(5).toString()).param("bancoEmisor","Banco"),"aprobado@quickbid.demo").andExpect(status().isUnprocessableEntity());}
 @Test void chequeConFormatoInvalidoEsError()throws Exception{MockMultipartFile bad=new MockMultipartFile("fotoAnverso","a.png","image/png","falso".getBytes()),ok=new MockMultipartFile("fotoReverso","b.png","image/png",png());request(multipart("/api/usuario/medios-pago").file(bad).file(ok).param("moneda","ARS").param("nacional","true").param("titular","Ana").param("numeroCheque","CH-2").param("monto","1000").param("fechaVencimiento",LocalDate.now().plusDays(5).toString()).param("bancoEmisor","Banco"),"aprobado@quickbid.demo").andExpect(status().isUnprocessableEntity()).andExpect(jsonPath("$.errors[0].code").value("FILE_TYPE_NOT_SUPPORTED"));}
 @Test void duplicadoEs409()throws Exception{var req=post("/api/usuario/medios-pago").contentType(MediaType.APPLICATION_JSON).content(card("5555555555554444"));request(req,"multa@quickbid.demo").andExpect(status().isCreated());request(post("/api/usuario/medios-pago").contentType(MediaType.APPLICATION_JSON).content(card("5555555555554444")),"multa@quickbid.demo").andExpect(status().isConflict()).andExpect(jsonPath("$.errors[0].code").value("PAYMENT_METHOD_DUPLICATE"));}
 @Test void eliminaMedioPropioLogicamente()throws Exception{request(delete("/api/usuario/medios-pago/5005"),"multa@quickbid.demo").andExpect(status().isOk());assertEquals("eliminado",jdbc.queryForObject("SELECT estado FROM app_medios_pago WHERE id=5005",String.class));}
 @Test void eliminarMedioAjenoEs403()throws Exception{request(delete("/api/usuario/medios-pago/5004"),"aprobado@quickbid.demo").andExpect(status().isForbidden()).andExpect(jsonPath("$.errors[0].code").value("RESOURCE_NOT_OWNED"));}
 @Test void eliminarMedioAsociadoEs409()throws Exception{request(delete("/api/usuario/medios-pago/5001"),"aprobado@quickbid.demo").andExpect(status().isConflict()).andExpect(jsonPath("$.errors[0].code").value("PAYMENT_METHOD_IN_USE"));}
 @Test void multaPendienteBloqueaEliminacion()throws Exception{jdbc.update("INSERT INTO app_compras(id,subasta_id,item_catalogo_id,producto_id,cuenta_comprador_id,medio_pago_id,monto_adjudicacion,moneda,estado) VALUES (13999,6003,8003,1003,3002,5005,1000,'USD','completada')");jdbc.update("INSERT INTO app_multas(id,cuenta_id,compra_id,monto,moneda,estado) VALUES (14999,3002,13999,100,'USD','pendiente')");request(delete("/api/usuario/medios-pago/5005"),"multa@quickbid.demo").andExpect(status().isConflict()).andExpect(jsonPath("$.errors[0].code").value("PAYMENT_METHOD_IN_USE"));}
 @Test void marcaPrincipalPorMoneda()throws Exception{request(patch("/api/usuario/medios-pago/5002/principal"),"aprobado@quickbid.demo").andExpect(status().isOk()).andExpect(jsonPath("$.data.principal").value(true));}
 @Test void principalAjenoEs403()throws Exception{request(patch("/api/usuario/medios-pago/5004/principal"),"aprobado@quickbid.demo").andExpect(status().isForbidden());}
 @Test void principalPendienteEs409()throws Exception{request(patch("/api/usuario/medios-pago/5003/principal"),"aprobado@quickbid.demo").andExpect(status().isConflict()).andExpect(jsonPath("$.errors[0].code").value("PAYMENT_METHOD_NOT_VERIFIED"));}
 @Test void endpointSinTokenEs401()throws Exception{mvc.perform(get("/api/usuario/medios-pago")).andExpect(status().isUnauthorized());}
 private ResultActions request(org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder b,String email)throws Exception{return mvc.perform(b.header("Authorization","Bearer "+token(email)));}
 private ResultActions request(org.springframework.test.web.servlet.request.MockMultipartHttpServletRequestBuilder b,String email)throws Exception{return mvc.perform(b.header("Authorization","Bearer "+token(email)));}
 private String token(String email)throws Exception{String json=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\""+email+"\",\"clave\":\"Demo123!\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();return JsonPath.read(json,"$.data.accessToken");}
 private String card(String pan){return "{\"tipo\":\"tarjeta\",\"moneda\":\"ARS\",\"nacional\":true,\"titular\":\"Titular Demo\",\"numeroTarjeta\":\""+pan+"\",\"cvv\":\"123\",\"vencimientoMes\":12,\"vencimientoAnio\":2030,\"marca\":\"Visa\"}";} private byte[] png(){return new byte[]{(byte)137,80,78,71,13,10,26,10};}
}
