-- QuickBid-owned schema. New application behavior belongs in app_* tables only.

CREATE TABLE app_archivos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_cuenta_id bigint,
    tipo_contexto varchar(50) NOT NULL,
    filename_original varchar(255) NOT NULL,
    content_type varchar(100) NOT NULL,
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    storage_path varchar(500) NOT NULL,
    checksum varchar(128) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_solicitudes_registro (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(320) NOT NULL,
    nombre varchar(150) NOT NULL,
    apellido varchar(150) NOT NULL,
    domicilio_legal varchar(250) NOT NULL,
    id_pais_origen integer NOT NULL REFERENCES paises (numero),
    foto_frente_dni_archivo_id bigint REFERENCES app_archivos (id),
    foto_dorso_dni_archivo_id bigint REFERENCES app_archivos (id),
    estado varchar(40) NOT NULL CHECK (estado IN (
        'pendiente_etapa2', 'pendiente_revision', 'rechazado',
        'aprobada_pendiente_finalizacion', 'completada', 'expirada'
    )),
    motivo_rechazo varchar(500),
    setup_token_hash varchar(128),
    setup_token_expires_at timestamp with time zone,
    setup_token_used_at timestamp with time zone,
    aprobado_por_empleado_id integer REFERENCES empleados (identificador),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_activity_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_app_solicitudes_registro_email_activa
    ON app_solicitudes_registro (lower(email))
    WHERE estado NOT IN ('rechazado', 'completada', 'expirada');

CREATE TABLE app_cuentas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id integer NOT NULL UNIQUE REFERENCES personas (identificador),
    cliente_id integer NOT NULL UNIQUE REFERENCES clientes (identificador),
    email varchar(320) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    estado varchar(40) NOT NULL CHECK (estado IN (
        'activa', 'restriccion_multa', 'bloqueada_permanente', 'deshabilitada_admin'
    )),
    puntos integer NOT NULL DEFAULT 0 CHECK (puntos >= 0),
    categoria_calculada varchar(10) NOT NULL CHECK (categoria_calculada IN (
        'comun', 'especial', 'plata', 'oro', 'platino'
    )),
    ultimo_acceso_at timestamp with time zone,
    intentos_login integer NOT NULL DEFAULT 0 CHECK (intentos_login >= 0),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE app_archivos
    ADD CONSTRAINT fk_app_archivos_owner_cuenta
    FOREIGN KEY (owner_cuenta_id) REFERENCES app_cuentas (id);

CREATE TABLE app_refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL REFERENCES app_cuentas (id),
    token_hash varchar(128) NOT NULL UNIQUE,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_agent varchar(500),
    ip varchar(64)
);

CREATE TABLE app_password_reset_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL REFERENCES app_cuentas (id),
    token_hash varchar(128) NOT NULL UNIQUE,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_categoria_puntos (
    categoria varchar(10) PRIMARY KEY CHECK (categoria IN ('comun', 'especial', 'plata', 'oro', 'platino')),
    puntos_minimos integer NOT NULL CHECK (puntos_minimos >= 0),
    orden integer NOT NULL UNIQUE CHECK (orden > 0)
);

CREATE TABLE app_movimientos_puntos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL REFERENCES app_cuentas (id),
    delta integer NOT NULL,
    motivo varchar(100) NOT NULL,
    referencia_tipo varchar(50),
    referencia_id bigint,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_documentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo varchar(60) NOT NULL,
    referencia_tipo varchar(50) NOT NULL,
    referencia_id bigint NOT NULL,
    archivo_id bigint NOT NULL REFERENCES app_archivos (id),
    estado varchar(30) NOT NULL DEFAULT 'disponible' CHECK (estado IN ('generando', 'disponible', 'anulado')),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_medios_pago (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL REFERENCES app_cuentas (id),
    tipo varchar(30) NOT NULL CHECK (tipo IN ('tarjeta', 'cuenta_bancaria', 'cheque_certificado')),
    moneda varchar(3) NOT NULL CHECK (moneda IN ('ARS', 'USD')),
    estado varchar(30) NOT NULL CHECK (estado IN ('pendiente_verificacion', 'verificado', 'rechazado', 'vencido', 'eliminado')),
    principal boolean NOT NULL DEFAULT false,
    nacional boolean NOT NULL,
    alias_visible varchar(100),
    ultimos_4 varchar(4),
    titular varchar(200) NOT NULL,
    hash_identificador varchar(128) NOT NULL,
    limite_monto decimal(18, 2),
    consumo_actual decimal(18, 2) NOT NULL DEFAULT 0 CHECK (consumo_actual >= 0),
    saldo_garantia decimal(18, 2),
    verificado_hasta timestamp with time zone,
    verificado_por_empleado_id integer REFERENCES empleados (identificador),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT chk_app_medios_pago_limite CHECK (limite_monto IS NULL OR limite_monto >= 0),
    CONSTRAINT chk_app_medios_pago_saldo CHECK (saldo_garantia IS NULL OR saldo_garantia >= 0)
);

CREATE UNIQUE INDEX uq_app_medios_pago_identificador_activo
    ON app_medios_pago (cuenta_id, hash_identificador)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uq_app_medios_pago_principal_moneda
    ON app_medios_pago (cuenta_id, moneda)
    WHERE principal = true AND deleted_at IS NULL;

CREATE TABLE app_tarjetas (
    medio_pago_id bigint PRIMARY KEY REFERENCES app_medios_pago (id),
    marca varchar(50),
    vencimiento_mes smallint NOT NULL CHECK (vencimiento_mes BETWEEN 1 AND 12),
    vencimiento_anio smallint NOT NULL
);

CREATE TABLE app_cuentas_bancarias (
    medio_pago_id bigint PRIMARY KEY REFERENCES app_medios_pago (id),
    numero_cuenta_hash varchar(128),
    cbu_cvu_hash varchar(128),
    nombre_banco varchar(150) NOT NULL,
    alias varchar(100)
);

CREATE TABLE app_cheques_certificados (
    medio_pago_id bigint PRIMARY KEY REFERENCES app_medios_pago (id),
    numero_cheque_hash varchar(128) NOT NULL,
    monto decimal(18, 2) NOT NULL CHECK (monto > 0),
    fecha_vencimiento date NOT NULL,
    banco_emisor varchar(150) NOT NULL,
    foto_anverso_archivo_id bigint NOT NULL REFERENCES app_archivos (id),
    foto_reverso_archivo_id bigint NOT NULL REFERENCES app_archivos (id)
);

CREATE TABLE app_subasta_ext (
    subasta_id integer PRIMARY KEY REFERENCES subastas (identificador),
    titulo varchar(200) NOT NULL,
    descripcion varchar(1000),
    moneda varchar(3) NOT NULL CHECK (moneda IN ('ARS', 'USD')),
    segmento varchar(100),
    estado_operativo varchar(30) NOT NULL CHECK (estado_operativo IN (
        'programada', 'abierta', 'en_vivo', 'cerrada', 'finalizada'
    )),
    permite_inscripcion_online boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_subasta_estado_vivo (
    subasta_id integer PRIMARY KEY REFERENCES subastas (identificador),
    item_catalogo_activo_id integer REFERENCES "itemsCatalogo" (identificador),
    version bigint NOT NULL DEFAULT 0,
    usuarios_conectados integer NOT NULL DEFAULT 0 CHECK (usuarios_conectados >= 0),
    lote_iniciado_at timestamp with time zone,
    lote_finaliza_estimado_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_inscripciones_subasta (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subasta_id integer NOT NULL REFERENCES subastas (identificador),
    cuenta_id bigint NOT NULL REFERENCES app_cuentas (id),
    medio_pago_id bigint NOT NULL REFERENCES app_medios_pago (id),
    estado varchar(30) NOT NULL CHECK (estado IN ('pendiente_validacion', 'aprobada', 'rechazada', 'expirada')),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_app_inscripciones_subasta UNIQUE (subasta_id, cuenta_id)
);

CREATE TABLE app_pujas_live (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pujo_legacy_id integer REFERENCES pujos (identificador),
    subasta_id integer NOT NULL REFERENCES subastas (identificador),
    item_catalogo_id integer NOT NULL REFERENCES "itemsCatalogo" (identificador),
    cuenta_id bigint NOT NULL REFERENCES app_cuentas (id),
    medio_pago_id bigint NOT NULL REFERENCES app_medios_pago (id),
    monto decimal(18, 2) NOT NULL CHECK (monto > 0),
    moneda varchar(3) NOT NULL CHECK (moneda IN ('ARS', 'USD')),
    estado varchar(30) NOT NULL CHECK (estado IN (
        'pendiente', 'aceptada', 'rechazada', 'superada', 'ganadora', 'anulada_admin'
    )),
    secuencia bigint NOT NULL CHECK (secuencia > 0),
    version_estado bigint NOT NULL CHECK (version_estado >= 0),
    idempotency_key varchar(100) NOT NULL UNIQUE,
    motivo_rechazo varchar(500),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at timestamp with time zone,
    CONSTRAINT uq_app_pujas_live_secuencia UNIQUE (subasta_id, item_catalogo_id, secuencia)
);

CREATE TABLE app_direcciones_envio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL REFERENCES app_cuentas (id),
    alias varchar(80) NOT NULL,
    destinatario varchar(200) NOT NULL,
    calle varchar(200) NOT NULL,
    numero varchar(30) NOT NULL,
    piso varchar(30),
    codigo_postal varchar(20) NOT NULL,
    localidad varchar(120) NOT NULL,
    provincia varchar(120) NOT NULL,
    pais varchar(120) NOT NULL,
    telefono varchar(50),
    principal boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

CREATE UNIQUE INDEX uq_app_direcciones_envio_principal
    ON app_direcciones_envio (cuenta_id)
    WHERE principal = true AND deleted_at IS NULL;

CREATE TABLE app_compras (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subasta_id integer NOT NULL REFERENCES subastas (identificador),
    item_catalogo_id integer NOT NULL REFERENCES "itemsCatalogo" (identificador),
    producto_id integer NOT NULL REFERENCES productos (identificador),
    cuenta_comprador_id bigint REFERENCES app_cuentas (id),
    comprador_empresa boolean NOT NULL DEFAULT false,
    puja_id bigint REFERENCES app_pujas_live (id),
    monto_adjudicacion decimal(18, 2) NOT NULL CHECK (monto_adjudicacion > 0),
    moneda varchar(3) NOT NULL CHECK (moneda IN ('ARS', 'USD')),
    estado varchar(50) NOT NULL CHECK (estado IN (
        'adjudicacion_pendiente', 'multa_activa', 'pagos_extra_pendientes', 'pagada',
        'entrega_pendiente', 'retiro_pendiente', 'abandonada_por_incumplimiento_pago',
        'abandonada_por_incumplimiento_retiro', 'completada'
    )),
    medio_pago_id bigint REFERENCES app_medios_pago (id),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_app_compras_comprador CHECK (
        (comprador_empresa = true AND cuenta_comprador_id IS NULL)
        OR (comprador_empresa = false AND cuenta_comprador_id IS NOT NULL)
    ),
    CONSTRAINT uq_app_compras_item UNIQUE (item_catalogo_id)
);

CREATE TABLE app_multas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL REFERENCES app_cuentas (id),
    compra_id bigint NOT NULL REFERENCES app_compras (id),
    monto decimal(18, 2) NOT NULL CHECK (monto > 0),
    moneda varchar(3) NOT NULL CHECK (moneda IN ('ARS', 'USD')),
    porcentaje decimal(5, 2) NOT NULL DEFAULT 10 CHECK (porcentaje > 0),
    estado varchar(20) NOT NULL CHECK (estado IN ('pendiente', 'pagada', 'vencida', 'derivada')),
    vence_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at timestamp with time zone
);

CREATE TABLE app_pagos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id bigint REFERENCES app_compras (id),
    multa_id bigint REFERENCES app_multas (id),
    medio_pago_id bigint NOT NULL REFERENCES app_medios_pago (id),
    monto decimal(18, 2) NOT NULL CHECK (monto > 0),
    moneda varchar(3) NOT NULL CHECK (moneda IN ('ARS', 'USD')),
    estado varchar(20) NOT NULL CHECK (estado IN ('pendiente', 'aprobado', 'rechazado', 'anulado')),
    referencia_externa varchar(150),
    idempotency_key varchar(100) NOT NULL UNIQUE,
    error_codigo varchar(80),
    error_detalle varchar(500),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_app_pagos_referencia CHECK (compra_id IS NOT NULL OR multa_id IS NOT NULL)
);

CREATE TABLE app_entregas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id bigint NOT NULL UNIQUE REFERENCES app_compras (id),
    tipo varchar(10) NOT NULL CHECK (tipo IN ('envio', 'retiro')),
    direccion_envio_id bigint REFERENCES app_direcciones_envio (id),
    costo_envio decimal(18, 2) NOT NULL DEFAULT 0 CHECK (costo_envio >= 0),
    estado varchar(30) NOT NULL CHECK (estado IN ('pendiente', 'pagada', 'en_transito', 'lista_retiro', 'completada')),
    perdio_cobertura_seguro boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_solicitudes_consignacion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL REFERENCES app_cuentas (id),
    cliente_id integer NOT NULL REFERENCES clientes (identificador),
    producto_id integer REFERENCES productos (identificador),
    item_catalogo_id integer REFERENCES "itemsCatalogo" (identificador),
    subasta_id integer REFERENCES subastas (identificador),
    titulo varchar(200) NOT NULL,
    descripcion varchar(1000) NOT NULL,
    categoria_sugerida varchar(10) CHECK (categoria_sugerida IN ('comun', 'especial', 'plata', 'oro', 'platino')),
    historia text,
    artista_disenador varchar(250),
    fecha_objeto varchar(100),
    declaracion_propiedad boolean NOT NULL,
    acepta_devolucion_con_cargo boolean NOT NULL,
    estado varchar(50) NOT NULL CHECK (estado IN (
        'pendiente_revision', 'rechazo_inicial', 'documentacion_adicional', 'recepcion_pendiente',
        'revision_fisica', 'rechazo_revision_fisica', 'acuerdo_pendiente', 'acuerdo_aceptado',
        'acuerdo_rechazado', 'devolucion_pendiente', 'publicada', 'en_subasta', 'vendida',
        'comprada_por_empresa', 'liquidada', 'devolucion_incompleta'
    )),
    requiere_documentacion_origen boolean NOT NULL DEFAULT false,
    motivo_rechazo varchar(500),
    revisor_empleado_id integer REFERENCES empleados (identificador),
    valor_base_propuesto decimal(18, 2),
    moneda_propuesta varchar(3) CHECK (moneda_propuesta IN ('ARS', 'USD')),
    comision_comprador_pct decimal(5, 2),
    comision_vendedor_pct decimal(5, 2),
    acuerdo_texto text,
    acuerdo_enviado_at timestamp with time zone,
    acuerdo_aceptado_at timestamp with time zone,
    acuerdo_rechazado_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_app_consignacion_declaraciones CHECK (
        declaracion_propiedad = true AND acepta_devolucion_con_cargo = true
    ),
    CONSTRAINT chk_app_consignacion_valor CHECK (valor_base_propuesto IS NULL OR valor_base_propuesto > 0)
);

CREATE TABLE app_consignacion_fotos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id bigint NOT NULL REFERENCES app_solicitudes_consignacion (id),
    archivo_id bigint NOT NULL REFERENCES app_archivos (id),
    orden integer NOT NULL CHECK (orden > 0),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_app_consignacion_fotos_orden UNIQUE (solicitud_id, orden)
);

CREATE TABLE app_consignacion_documentos_origen (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id bigint NOT NULL REFERENCES app_solicitudes_consignacion (id),
    archivo_id bigint NOT NULL REFERENCES app_archivos (id),
    estado varchar(20) NOT NULL CHECK (estado IN ('pendiente', 'aprobado', 'rechazado')),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_consignacion_devoluciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id bigint NOT NULL REFERENCES app_solicitudes_consignacion (id),
    motivo varchar(500) NOT NULL,
    costo decimal(18, 2) NOT NULL CHECK (costo >= 0),
    moneda varchar(3) NOT NULL CHECK (moneda IN ('ARS', 'USD')),
    estado varchar(30) NOT NULL CHECK (estado IN ('pendiente_pago', 'pagada', 'enviada', 'retirada', 'incumplida')),
    pago_id bigint REFERENCES app_pagos (id),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_liquidaciones_consignacion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id bigint NOT NULL UNIQUE REFERENCES app_solicitudes_consignacion (id),
    compra_id bigint NOT NULL REFERENCES app_compras (id),
    monto_bruto decimal(18, 2) NOT NULL CHECK (monto_bruto > 0),
    comision decimal(18, 2) NOT NULL CHECK (comision >= 0),
    monto_neto decimal(18, 2) NOT NULL CHECK (monto_neto >= 0),
    cuenta_destino varchar(250) NOT NULL,
    estado varchar(20) NOT NULL CHECK (estado IN ('pendiente', 'pagada', 'rechazada')),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at timestamp with time zone
);

CREATE TABLE app_notificaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL REFERENCES app_cuentas (id),
    tipo varchar(60) NOT NULL,
    titulo varchar(200) NOT NULL,
    descripcion varchar(1000) NOT NULL,
    referencia_tipo varchar(50),
    referencia_id bigint,
    leida boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at timestamp with time zone
);

CREATE TABLE app_auditoria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_tipo varchar(20) NOT NULL CHECK (actor_tipo IN ('usuario', 'admin', 'sistema')),
    actor_id bigint,
    accion varchar(100) NOT NULL,
    entidad_tipo varchar(80) NOT NULL,
    entidad_id bigint,
    before_json text,
    after_json text,
    metadata_json text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_app_pujas_live_item_estado ON app_pujas_live (subasta_id, item_catalogo_id, estado);
CREATE INDEX idx_app_compras_cuenta_estado ON app_compras (cuenta_comprador_id, estado);
CREATE INDEX idx_app_multas_cuenta_estado ON app_multas (cuenta_id, estado);
CREATE INDEX idx_app_notificaciones_cuenta_leida ON app_notificaciones (cuenta_id, leida, created_at DESC);
CREATE INDEX idx_app_auditoria_entidad ON app_auditoria (entidad_tipo, entidad_id, created_at DESC);
