ALTER TABLE app_subasta_estado_vivo
    ADD COLUMN IF NOT EXISTS proximo_lote_programado_at timestamp with time zone;

ALTER TABLE app_subasta_estado_vivo
    ADD COLUMN IF NOT EXISTS subasta_finaliza_programado_at timestamp with time zone;

CREATE TABLE IF NOT EXISTS app_reservas_medio_pago (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medio_pago_id bigint NOT NULL REFERENCES app_medios_pago (id),
    puja_id bigint NOT NULL REFERENCES app_pujas_live (id),
    monto decimal(18, 2) NOT NULL CHECK (monto > 0),
    estado varchar(20) NOT NULL CHECK (estado IN ('activa', 'liberada', 'consumida')),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at timestamp with time zone,
    consumed_at timestamp with time zone,
    CONSTRAINT uq_app_reservas_medio_pago_puja UNIQUE (puja_id)
);

CREATE INDEX IF NOT EXISTS idx_app_reservas_medio_pago_medio_estado
    ON app_reservas_medio_pago (medio_pago_id, estado);

INSERT INTO app_reservas_medio_pago (medio_pago_id, puja_id, monto, estado)
SELECT p.medio_pago_id, p.id, p.monto, 'activa'
FROM app_pujas_live p
WHERE p.estado = 'aceptada'
  AND NOT EXISTS (
      SELECT 1 FROM app_reservas_medio_pago r WHERE r.puja_id = p.id
  );
