spring.application.name=quickbid



spring.datasource.url=jdbc:postgresql://localhost:5432/COMPLETARNOMBREDEBASEDEDATOSACÁ
spring.datasource.username=postgres
spring.datasource.password=COMPLETARCONTRASEÑAGENERALDEPOSTGREACÁ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true