spring.application.name=quickbid



spring.datasource.url=jdbc:postgresql://localhost:5432/baseQuickbid
spring.datasource.username=postgres
spring.datasource.password=PostgreBD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true